# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# pylint: skip-file

load("@rules_java//java:defs.bzl", "java_library")
load("//tools/bazel:junit5.bzl", "ozone_junit5_package")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "ozone-s3gateway",
    srcs = glob(["src/main/java/**/*.java"], allow_empty = True),
    resources = glob(["src/main/resources/**"], allow_empty = True),
    deps = [
        "//hadoop-hdds/cli-common:hdds-cli-common",
        "//hadoop-hdds/client:hdds-client",
        "//hadoop-hdds/common:hdds-common",
        "//hadoop-hdds/config:hdds-config",
        "//hadoop-hdds/framework:hdds-server-framework",
        "//hadoop-hdds/interface-client:hdds-interface-client",
        "//hadoop-ozone/client:ozone-client",
        "//hadoop-ozone/common:ozone-common",
        "//hadoop-ozone/interface-client:ozone-interface-client",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_dataformat_jackson_dataformat_xml",
        "@maven//:com_fasterxml_jackson_module_jackson_module_jaxb_annotations",
        "@maven//:com_github_stephenc_jcip_jcip_annotations",
        "@maven//:com_google_guava_guava",
        "@maven//:commons_codec_commons_codec",
        "@maven//:commons_io_commons_io",
        "@maven//:info_picocli_picocli",
        "@maven//:io_opentelemetry_opentelemetry_api",
        "@maven//:jakarta_annotation_jakarta_annotation_api",
        "@maven//:jakarta_ws_rs_jakarta_ws_rs_api",
        "@maven//:jakarta_xml_bind_jakarta_xml_bind_api",
        "@maven//:javax_annotation_javax_annotation_api",
        "@maven//:javax_enterprise_cdi_api",
        "@maven//:javax_inject_javax_inject",
        "@maven//:javax_servlet_javax_servlet_api",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_apache_hadoop_hadoop_auth",
        "@maven//:org_apache_hadoop_hadoop_common",
        "@maven//:org_apache_httpcomponents_httpclient",
        "@maven//:org_apache_httpcomponents_httpcore",
        "@maven//:org_apache_kerby_kerby_util",
        "@maven//:org_apache_ratis_ratis_common",
        "@maven//:org_eclipse_jetty_jetty_servlet",
        "@maven//:org_eclipse_jetty_jetty_webapp",
        "@maven//:org_glassfish_jersey_core_jersey_common",
        "@maven//:org_glassfish_jersey_core_jersey_server",
        "@maven//:org_slf4j_jul_to_slf4j",
        "@maven//:org_slf4j_slf4j_api",
    ],
)

java_library(
    name = "ozone-s3gateway-tests",
    testonly = True,
    tags = ["manual"],
    srcs = glob(["src/test/java/**/*.java"], allow_empty = True),
    resources = glob(["src/test/resources/**"], allow_empty = True),
    deps = [
        ":ozone-s3gateway",
        "//hadoop-ozone/client:ozone-client-tests",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_junit_jupiter",
    ],
)

# OZONE_JUNIT5_WIRED

ozone_junit5_package(
    name = "ozone-s3gateway-tests-pkg-org-apache-hadoop-ozone-protocolPB",
    package = "org.apache.hadoop.ozone.protocolPB",
    size = "large",
    tags = ["unit", "manual"],
    deps = [":ozone-s3gateway-tests"],
)

ozone_junit5_package(
    name = "ozone-s3gateway-tests-pkg-org-apache-hadoop-ozone-s3",
    package = "org.apache.hadoop.ozone.s3",
    size = "large",
    tags = ["unit", "manual"],
    deps = [":ozone-s3gateway-tests"],
)

ozone_junit5_package(
    name = "ozone-s3gateway-tests-pkg-org-apache-hadoop-ozone-s3-commontypes",
    package = "org.apache.hadoop.ozone.s3.commontypes",
    size = "large",
    tags = ["unit", "manual"],
    deps = [":ozone-s3gateway-tests"],
)

ozone_junit5_package(
    name = "ozone-s3gateway-tests-pkg-org-apache-hadoop-ozone-s3-endpoint",
    package = "org.apache.hadoop.ozone.s3.endpoint",
    size = "large",
    tags = ["unit", "manual"],
    deps = [":ozone-s3gateway-tests"],
)

ozone_junit5_package(
    name = "ozone-s3gateway-tests-pkg-org-apache-hadoop-ozone-s3-exception",
    package = "org.apache.hadoop.ozone.s3.exception",
    size = "large",
    tags = ["unit", "manual"],
    deps = [":ozone-s3gateway-tests"],
)

ozone_junit5_package(
    name = "ozone-s3gateway-tests-pkg-org-apache-hadoop-ozone-s3-metrics",
    package = "org.apache.hadoop.ozone.s3.metrics",
    size = "large",
    tags = ["unit", "manual"],
    deps = [":ozone-s3gateway-tests"],
)

ozone_junit5_package(
    name = "ozone-s3gateway-tests-pkg-org-apache-hadoop-ozone-s3-signature",
    package = "org.apache.hadoop.ozone.s3.signature",
    size = "large",
    tags = ["unit", "manual"],
    deps = [":ozone-s3gateway-tests"],
)

ozone_junit5_package(
    name = "ozone-s3gateway-tests-pkg-org-apache-hadoop-ozone-s3-util",
    package = "org.apache.hadoop.ozone.s3.util",
    size = "large",
    tags = ["unit", "manual"],
    deps = [":ozone-s3gateway-tests"],
)

ozone_junit5_package(
    name = "ozone-s3gateway-tests-pkg-org-apache-hadoop-ozone-s3secret",
    package = "org.apache.hadoop.ozone.s3secret",
    size = "large",
    tags = ["unit", "manual"],
    deps = [":ozone-s3gateway-tests"],
)

