version: 1
exclude:
  - "**/pom.xml"
  - "**/*.bazel"
  - "MODULE.bazel"
  - "MODULE.bazel.lock"
  - "**/maven_artifacts.bzl"
  - "**/.mvn/**"
  - "**/maven-settings.xml"
  - "**/checkstyle.xml"
rules:
  duplication:
    enabled: false
  python:
    complexity:
      enabled: false
