# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

exports_files([
    "defs.bzl",
    "aspectj.bzl",
    "java_proto.bzl",
    "ratis_proto_rewrite.bzl",
    "maven_artifacts.bzl",
    "extra_maven_artifacts.bzl",
])

sh_binary(
    name = "protoc",
    srcs = ["protoc_wrapper.sh"],
    visibility = ["//visibility:public"],
)

exports_files(["facade/package-info.java"])

filegroup(
    name = "facade_src",
    srcs = ["facade/package-info.java"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "protoc_gen_grpc_java",
    srcs = ["protoc_gen_grpc_java_wrapper.sh"],
    visibility = ["//visibility:public"],
)
