#!/usr/bin/env python3
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generate maven_artifacts.bzl from the root pom.xml dependencyManagement section."""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
POM = ROOT / "pom.xml"
OUT = Path(__file__).resolve().parent / "maven_artifacts.bzl"
NS = {"m": "http://maven.apache.org/POM/4.0.0"}

# Not published to Maven Central (optional / reactor-only coordinates).
SKIP_ARTIFACT_IDS = frozenset({
    "ratis-proto-shaded",
})


def _properties(pom_root: ET.Element) -> dict[str, str]:
    props: dict[str, str] = {}
    for child in pom_root.find("m:properties", NS) or []:
        tag = child.tag.split("}", 1)[-1]
        props[tag] = (child.text or "").strip()
    return props


def resolve(version: str, props: dict[str, str], depth: int = 0) -> str:
    if depth > 8 or not version.startswith("${"):
        return version
    key = version[2:-1]
    return resolve(props.get(key, version), props, depth + 1)


def _dependency_coords(dep: ET.Element, props: dict[str, str]) -> str | None:
    group = dep.find("m:groupId", NS)
    artifact = dep.find("m:artifactId", NS)
    if group is None or artifact is None:
        return None
    group_id = (group.text or "").strip()
    artifact_id = (artifact.text or "").strip()
    if group_id == "org.apache.ozone":
        return None
    dep_type = (dep.find("m:type", NS).text or "jar").strip() if dep.find("m:type", NS) is not None else "jar"
    if dep_type == "pom" or artifact_id.endswith("-bom") or artifact_id in SKIP_ARTIFACT_IDS:
        return None
    version_el = dep.find("m:version", NS)
    if version_el is None or not version_el.text:
        return None
    ver = resolve(version_el.text.strip(), props)
    if not ver or ver.startswith("${"):
        return None
    return f"{group_id}:{artifact_id}:{ver}"


def main() -> int:
    pom_root = ET.parse(POM).getroot()
    props = _properties(pom_root)
    dm = pom_root.find("m:dependencyManagement/m:dependencies", NS)
    if dm is None:
        print("dependencyManagement not found", file=sys.stderr)
        return 1
    deps: set[str] = set()
    for dep in dm.findall("m:dependency", NS):
        coords = _dependency_coords(dep, props)
        if coords:
            deps.add(coords)

    lines = [
        "# Generated by tools/bazel/generate_maven_artifacts.py — do not edit by hand.",
        "MAVEN_ARTIFACTS = [",
    ]
    for dep in sorted(deps):
        lines.append(f'    "{dep}",')
    lines.append("]")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(deps)} artifacts to {OUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
