---
linux_distro: ['bionic', 'el7', 'el8', 'focal', 'sles12']
additional_jars: ['rocksdbjni*.jar',
                  'commons-text*.jar',
                  'snakeyaml*.jar',
                  'spring-*.jar',
                  'jetty-*.jar',
                  'jackson2*',
                  'netty-*.jar',
                  'joda-time-*.jar',
                  'jackson-*.jar',
                  'nimbus-jose']
