ARG OZONE_RUNNER_IMAGE=apache/ozone-runner
ARG OZONE_RUNNER_VERSION=20241108-jdk17-1

FROM ${OZONE_RUNNER_IMAGE}:${OZONE_RUNNER_VERSION}

ARG OZONE_BIN

ADD --chown=hadoop:users ${OZONE_BIN} /opt/hadoop/

WORKDIR /opt/hadoop

ENV OZONE_CONF_DIR=/etc/hadoop
ENV OZONE_LOG_DIR=/var/log/hadoop
ENV PATH="/opt/hadoop/bin:/opt/hadoop/sbin:${PATH}"