# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "ozone-tools",
    srcs = glob(["src/main/java/**/*.java"], allow_empty = True),
    resources = glob(["src/main/resources/**"], allow_empty = True),
    deps = [
        "//hadoop-hdds/cli-common:hdds-cli-common",
        "//hadoop-hdds/common:hdds-common",
        "//hadoop-hdds/config:hdds-config",
        "//hadoop-ozone/common:ozone-common",
        "@maven//:ch_qos_reload4j_reload4j",
        "@maven//:com_google_guava_guava",
        "@maven//:info_picocli_picocli",
        "@maven//:jakarta_xml_bind_jakarta_xml_bind_api",
        "@maven//:org_apache_hadoop_hadoop_common",
        "@maven//:org_apache_ratis_ratis_common",
        "@maven//:org_apache_ratis_ratis_shell",
        "@maven//:org_kohsuke_metainf_services_metainf_services",
        "@maven//:org_reflections_reflections",
        "@maven//:org_slf4j_slf4j_api",
    ],
)

java_library(
    name = "ozone-tools-tests",
    testonly = True,
    tags = ["manual"],
    srcs = glob(["src/test/java/**/*.java"], allow_empty = True),
    resources = glob(["src/test/resources/**"], allow_empty = True),
    deps = [
        ":ozone-tools",
        "//hadoop-hdds/common:hdds-common-tests",
        "//hadoop-hdds/container-service:hdds-container-service-tests",
        "//hadoop-hdds/framework:hdds-server-framework-tests",
        "//hadoop-hdds/test-utils:hdds-test-utils",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_junit_jupiter",
    ],
)
